#!/bin/bash

# Quick Start Script for Video Clipping Platform Deployment
# Run this on your fresh VPS to get started quickly

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}"
cat << "EOF"
  ______ _      _       _            
 / _____) |    (_)     (_)           
| /     | |     _  ____ _ ____   ____
| |     | |    | |/ ___) |  _ \ / _  |
| \_____| |____| | |   | | | | ( (_| |
 \______)______)_|_|   |_|_| |_|\___ |
                                (_____|
                                       
   Video Processing Platform
   Production Deployment
EOF
echo -e "${NC}"

echo -e "${GREEN}🚀 Welcome to the Video Clipping Platform Quick Start!${NC}"
echo ""
echo "This script will help you deploy the platform to your VPS."
echo ""

# Check if running as root
if [[ $EUID -eq 0 ]]; then
    echo -e "${RED}❌ Please don't run this script as root${NC}"
    echo "Create a regular user with sudo privileges instead:"
    echo "  adduser deploy"
    echo "  usermod -aG sudo deploy"
    echo "  su - deploy"
    exit 1
fi

# Gather required information
echo -e "${BLUE}📝 Please provide the following information:${NC}"
echo ""

read -p "Your domain name (e.g., example.com): " DOMAIN
read -p "Your email for SSL certificates: " EMAIL
read -p "Repository URL (or press Enter for current directory): " REPO_URL

# Validate domain
if [[ ! "$DOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9]\.[a-zA-Z]{2,}$ ]]; then
    echo -e "${RED}❌ Invalid domain format${NC}"
    exit 1
fi

# Validate email
if [[ ! "$EMAIL" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
    echo -e "${RED}❌ Invalid email format${NC}"
    exit 1
fi

echo ""
echo -e "${YELLOW}📋 Configuration Summary:${NC}"
echo "Domain: $DOMAIN"
echo "Admin Domain: admin.$DOMAIN"
echo "Email: $EMAIL"
echo ""

read -p "Proceed with deployment? (y/N): " CONFIRM
if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Deployment cancelled."
    exit 0
fi

echo ""
echo -e "${BLUE}🔧 Starting deployment process...${NC}"

# Step 1: Update system and install dependencies
echo -e "${GREEN}Step 1: Installing dependencies...${NC}"
if command -v docker &> /dev/null && command -v docker-compose &> /dev/null; then
    echo "✅ Dependencies already installed"
else
    curl -fsSL https://raw.githubusercontent.com/your-repo/clipping/main/deployment/vps-setup.sh | bash
    echo "⚠️  Please log out and log back in, then run this script again."
    exit 0
fi

# Step 2: Clone or setup repository
echo -e "${GREEN}Step 2: Setting up application...${NC}"
APP_DIR="/opt/clipping"

if [[ ! -d "$APP_DIR" ]]; then
    sudo mkdir -p "$APP_DIR"
    sudo chown $USER:$USER "$APP_DIR"
fi

cd "$APP_DIR"

if [[ -n "$REPO_URL" ]]; then
    if [[ ! -d ".git" ]]; then
        git clone "$REPO_URL" .
    else
        git pull origin main
    fi
fi

# Step 3: Generate configuration
echo -e "${GREEN}Step 3: Generating configuration...${NC}"

# Generate secrets
JWT_SECRET=$(openssl rand -base64 32)
JWT_REFRESH_SECRET=$(openssl rand -base64 32)
REDIS_PASSWORD=$(openssl rand -base64 32)
ADMIN_PASSWORD=$(openssl rand -base64 16)

# Create production environment file
cat > .env.production << EOF
# Generated by quick-start script
DOMAIN=$DOMAIN
ADMIN_DOMAIN=admin.$DOMAIN

# API Configuration
NEXT_PUBLIC_API_URL=https://$DOMAIN/api
NEXT_PUBLIC_WS_URL=wss://$DOMAIN/ws
CORS_ORIGIN=https://$DOMAIN,https://www.$DOMAIN

# Security
JWT_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
REDIS_PASSWORD=$REDIS_PASSWORD

# Admin
REDIS_COMMANDER_USER=admin
REDIS_COMMANDER_PASSWORD=$ADMIN_PASSWORD

# SSL
LETSENCRYPT_EMAIL=$EMAIL

# Storage (local by default)
STORAGE_TYPE=local

# Performance
AI_WORKER_CONCURRENCY=2
VIDEO_WORKER_CONCURRENCY=2
TRANSCRIPTION_WORKER_CONCURRENCY=1
WHISPER_TIMESTAMP_WORKER_CONCURRENCY=1

# Logging
LOG_LEVEL=info
NODE_ENV=production
DEBUG=false
EOF

echo "✅ Configuration file created"

# Step 4: Update nginx configuration
echo -e "${GREEN}Step 4: Configuring web server...${NC}"
sed -i "s/YOUR_DOMAIN_HERE/$DOMAIN/g" deployment/nginx/conf.d/clipping.conf
echo "✅ Nginx configuration updated"

# Step 5: Deploy application
echo -e "${GREEN}Step 5: Deploying application...${NC}"
./deployment/deploy.sh

# Step 6: Create admin credentials
echo -e "${GREEN}Step 6: Setting up admin access...${NC}"
echo "admin:$(openssl passwd -apr1 $ADMIN_PASSWORD)" | sudo tee deployment/nginx/.htpasswd > /dev/null
echo "✅ Admin credentials created"

# Display results
echo ""
echo -e "${GREEN}🎉 Deployment completed successfully!${NC}"
echo ""
echo -e "${BLUE}📋 Access Information:${NC}"
echo "🌐 Website: https://$DOMAIN"
echo "🔧 Admin Panel: https://admin.$DOMAIN"
echo "👤 Admin Username: admin"
echo "🔑 Admin Password: $ADMIN_PASSWORD"
echo ""
echo -e "${YELLOW}⚠️  Important Security Notes:${NC}"
echo "1. Save the admin password: $ADMIN_PASSWORD"
echo "2. Configure Cloudflare DNS to point to this server"
echo "3. Update firewall rules if needed"
echo "4. Set up regular backups"
echo ""
echo -e "${BLUE}📖 Next Steps:${NC}"
echo "1. Follow the Cloudflare setup guide: ./deployment/CLOUDFLARE_SETUP.md"
echo "2. Test your deployment: curl https://$DOMAIN/api/health"
echo "3. Monitor logs: ./deployment/deploy.sh logs"
echo "4. Check service status: ./deployment/deploy.sh status"
echo ""
echo -e "${GREEN}📞 Support:${NC}"
echo "• Documentation: ./deployment/README.md"
echo "• Troubleshooting: Check logs and verify configuration"
echo "• Updates: git pull && ./deployment/deploy.sh restart"
echo ""
echo -e "${GREEN}✨ Your Video Clipping Platform is ready! ✨${NC}" 