#!/bin/bash

# Development Environment Help
# This script shows all available development commands

echo "🔧 Video Clipping Platform - Development Commands"
echo "================================================="
echo ""
echo "Setup Commands:"
echo "├── ./scripts/dev-setup.sh    - Initial environment setup"
echo "└── ./scripts/dev-clean.sh    - Clean and reset environment"
echo ""
echo "Service Management:"
echo "├── ./scripts/dev-start.sh    - Start all services"
echo "├── ./scripts/dev-stop.sh     - Stop all services"
echo "├── ./scripts/dev-restart.sh  - Restart all services"
echo "└── ./scripts/dev-status.sh   - Show service status"
echo ""
echo "Monitoring:"
echo "├── ./scripts/dev-logs.sh [service]  - View logs (all or specific service)"
echo "└── ./scripts/dev-test.sh            - Test all worker services"
echo ""
echo "Available Services:"
echo "├── redis              - Redis database for job queues"
echo "├── ollama             - Ollama AI service for analysis"
echo "├── queue-service      - Queue management and monitoring"
echo "├── ai-worker          - AI analysis worker"
echo "├── transcription-worker        - Audio transcription worker"
echo "├── whisper-timestamp-worker    - Precise timestamp worker"
echo "├── video-worker       - Video processing worker"
echo "├── storage-service    - File storage service (future)"
echo "├── api-gateway        - API gateway service (future)"
echo "└── redis-commander    - Redis web interface"
echo ""
echo "Web Interfaces:"
echo "├── Queue Dashboard: http://localhost:3004/admin/queues"
echo "├── Queue API: http://localhost:3004/api"
echo "├── Redis Commander: http://localhost:8081"
echo "└── Ollama API: http://localhost:11434"
echo ""
echo "Quick Start:"
echo "1. Run setup: ./scripts/dev-setup.sh"
echo "2. Start services: ./scripts/dev-start.sh"
echo "3. View status: ./scripts/dev-status.sh"
echo "4. Test workers: ./scripts/dev-test.sh"
echo ""
echo "Troubleshooting:"
echo "├── Check logs: ./scripts/dev-logs.sh [service-name]"
echo "├── Restart service: docker-compose restart [service-name]"
echo "├── Rebuild service: docker-compose build [service-name]"
echo "└── Clean environment: ./scripts/dev-clean.sh"
echo ""
echo "For more information, see:"
echo "├── ARCHITECTURE_REFACTOR.md - Architecture documentation"
echo "├── environment.example - Environment variables"
echo "└── docker-compose.yml - Service configuration" 